// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.ConfigSnapshot>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.ConfigSnapshot>;
