// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAudioTools():Promise<main.AudioToolsStatus>;

export function DeleteSound(arg1:string):Promise<main.ConfigSnapshot>;

export function DeleteSounds(arg1:Array<string>):Promise<main.ConfigSnapshot>;

export function GetSoundPreviewDataURL(arg1:string):Promise<string>;

export function ImportSoundPaths(arg1:Array<string>):Promise<main.ConfigSnapshot>;

export function ImportSoundWithPicker():Promise<main.ConfigSnapshot>;

export function LoadConfig():Promise<main.ConfigSnapshot>;

export function ProbeSoundDuration(arg1:string):Promise<main.ConfigSnapshot>;

export function ProcessSound(arg1:string):Promise<main.ConfigSnapshot>;

export function ProcessSounds(arg1:Array<string>):Promise<main.ConfigSnapshot>;

export function RenameSound(arg1:main.RenameSoundRequest):Promise<main.ConfigSnapshot>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.ConfigSnapshot>;

export function SelectSoundFiles():Promise<Array<string>>;
